### ISSUE TITLE
Please document how exactly does this differ from github.com/client9/misspell

### ISSUE THREAD

**Issue by tv42** [alexkohler/identypo#1]
github.com/client9/misspell also provides a command-line to fix spelling errors. It *seems* like the differences are:

- misspell processes either only Go comments, or all input as pure text; identypo processes AST nodes that are identifiers
- identypo recognizes CamelCaseIdentifiers as multiple words; misspell does not

Is this correct? Are there more relevant differences?

**Comment by alexkohler** [comment]
> misspell processes either only Go comments, or all input as pure text; identypo processes AST nodes that are identifiers

That's correct - identypo processes identifiers (variables, functions, etc.), but does not parse comments.

> identypo recognizes CamelCaseIdentifiers as multiple words; misspell does not
That's also correct - identypo will split all camel-cased identifiers into individual words and analyze whether or not they're spelled correctly (actually using client9's algorithm to determine whether or a given word is spelled correctly).

You bring up a good point - I'll add a section to clarify the differences 👍

**Comment by alexkohler** [comment]
I've added a section to clarify the differences. Please let me know if you have any other comments/concerns. 😃
